# Generated by Django 5.2.12 on 2026-05-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='info',
            name='image',
        ),
        migrations.RemoveField(
            model_name='info',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
