# Generated by Django 5.2.12 on 2026-05-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_remove_comment_user_remove_info_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='favorite_users',
        ),
    ]
