# Generated by Django 5.2.12 on 2026-03-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_info_created_alter_info_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='school_image',
            field=models.ImageField(blank=True, null=True, upload_to='festival_images/'),
        ),
    ]
