# Generated by Django 5.2.12 on 2026-05-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='festival_images/'),
        ),
        migrations.AddField(
            model_name='info',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='festival_images/poster/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
