# Generated by Django 5.2.12 on 2026-03-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0010_rename_created_at_review_created_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='school',
        ),
    ]
