# Generated by Django 5.2.12 on 2026-04-05 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0014_info_favorite_infos_alter_info_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='favorite_infos',
        ),
        migrations.AddField(
            model_name='info',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
