# Generated by Django 5.2.12 on 2026-03-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Festival_info',
            new_name='Info',
        ),
    ]
