# Generated by Django 5.2.12 on 2026-03-23 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_rename_festival_info_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(),
        ),
    ]
