# Generated by Django 5.2.12 on 2026-03-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_info_school_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='school_image',
            new_name='image',
        ),
    ]
