# Generated by Django 5.2.12 on 2026-03-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_user_remove_review_title_review_info_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='contents',
        ),
    ]
