# Generated by Django 5.2.12 on 2026-03-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0008_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likearea',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likeschool',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
    ]
