# Generated by Django 5.2.12 on 2026-04-05 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0012_alter_post_user_alter_review_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='info',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='festival_images/poster/'),
        ),
        migrations.AddField(
            model_name='info',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
