# Generated by Django 5.2.12 on 2026-04-05 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0013_rename_date_info_end_date_info_poster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='favorite_infos',
            field=models.ManyToManyField(blank=True, related_name='favorite_infos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='info',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
