# Generated by Django 5.2.12 on 2026-05-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_birth_alter_customuser_likearea_and_more'),
        ('accounts', '0003_alter_customuser_profile'),
    ]

    operations = [
    ]
